version: '3'
services:
  db:
    container_name: postgresDB
    image: postgres
    user: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
